# Generated by Django 4.2.27 on 2026-02-09 14:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Future Self', max_length=255)),
                ('appearance', models.CharField(choices=[('youthful', 'Youthful'), ('mature', 'Mature'), ('gentle', 'Gentle'), ('energetic', 'Energetic')], default='gentle', max_length=50)),
                ('expression', models.CharField(choices=[('warm', 'Warm'), ('hopeful', 'Hopeful'), ('peaceful', 'Peaceful'), ('joyful', 'Joyful')], default='warm', max_length=50)),
                ('tone', models.CharField(choices=[('encouraging', 'Encouraging'), ('gentle', 'Gentle'), ('inspiring', 'Inspiring'), ('celebratory', 'Celebratory')], default='encouraging', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avatar Configuration',
                'verbose_name_plural': 'Avatar Configurations',
                'db_table': 'avatar_config',
            },
        ),
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatigue_level', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('consistency_score', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mood_level', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User State',
                'verbose_name_plural': 'User States',
                'db_table': 'user_state',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_completed_onboarding', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar_config', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='main.avatarconfig')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carepath_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('daily', 'Daily'), ('challenge', 'Challenge')], max_length=50)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FutureSelfMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('letter', 'Letter'), ('voice', 'Voice'), ('advice', 'Advice')], max_length=50)),
                ('content', models.TextField()),
                ('unlock_progress', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_self_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Future Self Message',
                'verbose_name_plural': 'Future Self Messages',
                'db_table': 'future_self_messages',
                'ordering': ['unlock_progress'],
            },
        ),
        migrations.CreateModel(
            name='ConstellationStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_type', models.CharField(choices=[('difficult-day', 'Difficult Day'), ('milestone', 'Milestone'), ('return', 'Return After Pause'), ('emotional-challenge', 'Emotional Challenge')], max_length=50)),
                ('mood', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField()),
                ('size', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.75), django.core.validators.MaxValueValidator(1.25)])),
                ('x', models.FloatField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(85)])),
                ('y', models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(80)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constellation_stars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Constellation Star',
                'verbose_name_plural': 'Constellation Stars',
                'db_table': 'constellation_stars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdaptiveChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('comfort', 'Comfort'), ('flow', 'Flow'), ('momentum', 'Momentum')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adaptive Challenge',
                'verbose_name_plural': 'Adaptive Challenges',
                'db_table': 'adaptive_challenges',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
