# Generated by Django 4.2.27 on 2026-02-11 10:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Every day'), ('every-2-days', 'Every 2 days'), ('every-3-days', 'Every 3 days'), ('weekly', 'Every week'), ('twice-weekly', 'Twice a week'), ('twice-daily', 'Twice a day'), ('three-times-daily', 'Three times a day'), ('custom', 'Custom')], max_length=50)),
                ('custom_frequency_days', models.IntegerField(blank=True, null=True)),
                ('timing', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('anytime', 'Anytime')], default='anytime', max_length=50)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('dosage', models.CharField(blank=True, max_length=255)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Template',
                'db_table': 'task_templates',
                'ordering': ['-is_important', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(blank=True, max_length=255)),
                ('treatment_type', models.CharField(blank=True, max_length=255)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('hospital', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('duration_weeks', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Treatment Information',
                'db_table': 'treatment_info',
            },
        ),
        migrations.AlterModelOptions(
            name='avatarconfig',
            options={'verbose_name': 'Avatar Configuration'},
        ),
        migrations.AlterModelOptions(
            name='constellationstar',
            options={'ordering': ['-created_at'], 'verbose_name': 'Constellation Star'},
        ),
        migrations.AlterModelOptions(
            name='futureselfmessage',
            options={'ordering': ['unlock_progress'], 'verbose_name': 'Future Self Message'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date', '-is_important', 'timing'], 'verbose_name': 'Task'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile'},
        ),
        migrations.AlterModelOptions(
            name='userstate',
            options={'verbose_name': 'User State'},
        ),
        migrations.AddField(
            model_name='avatarconfig',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='task',
            name='dosage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='quantity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='timing',
            field=models.CharField(default='anytime', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vio_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('user', 'title', 'date', 'timing')},
        ),
        migrations.DeleteModel(
            name='AdaptiveChallenge',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tasktemplate'),
        ),
    ]
