# Generated by Django 4.2.27 on 2026-02-12 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tasktemplate_treatmentinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentinfo',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentinfo',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
