# Generated by Django 4.2.27 on 2026-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_notification'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='main_notifi_user_id_eaabd3_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='avatar_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.CharField(default='👤', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reminder', 'Reminder'), ('breathing', 'Breathing'), ('challenge', 'Challenge'), ('achievement', 'Achievement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
