# Generated by Django 4.2.27 on 2026-02-13 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_notification_main_notifi_user_id_eaabd3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
